"""
Django settings for web_boda project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    def load_dotenv(*args, **kwargs):
        """Permite iniciar el proyecto si python-dotenv aún no está instalado."""
        return False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Las variables de entorno (credenciales de la base de datos y del
# administrador) viven en el archivo .env de la raiz del proyecto.
load_dotenv(BASE_DIR / '.env')


def _entorno(clave, defecto=''):
    return os.environ.get(clave, defecto)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _entorno('SECRET_KEY', 'django-insecure-9f3b1a7c2e0000000000000000000000000000000000')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _entorno('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'si')

ALLOWED_HOSTS = [host.strip() for host in _entorno('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_boda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_boda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# PostgreSQL: los datos vienen del archivo .env (DB_NAME, DB_USER, ...).

DB_ENGINE = _entorno('DB_ENGINE', 'django.db.backends.postgresql')
if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': _entorno('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': _entorno('DB_NAME', 'bddboda'),
            'USER': _entorno('DB_USER', 'postgres'),
            'PASSWORD': _entorno('DB_PASSWORD', ''),
            'HOST': _entorno('DB_HOST', 'localhost'),
            'PORT': _entorno('DB_PORT', '5432'),
        }
    }

# Credenciales del administrador del panel, definidas en .env.
ADMIN_USUARIO = _entorno('ADMIN_USUARIO', 'admin')
ADMIN_PASSWORD = _entorno('ADMIN_PASSWORD', '')
ADMIN_EMAIL = _entorno('ADMIN_EMAIL', 'admin@boda.local')
ADMIN_NOMBRE = _entorno('ADMIN_NOMBRE', 'Administrador')


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # build de React (Vite) y archivos publicos del frontend
    BASE_DIR / 'frontend' / 'dist',
    BASE_DIR / 'frontend' / 'public',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
