# Generated by Django 6.1.1 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('pases', models.PositiveSmallIntegerField(default=1, verbose_name='Pases asignados')),
                ('acompanantes', models.CharField(blank=True, max_length=300, verbose_name='Acompañantes')),
                ('asistencia', models.CharField(choices=[('si', 'Si asistiré'), ('no', 'No podré asistir')], default='si', max_length=4, verbose_name='Asistencia')),
                ('menu', models.CharField(blank=True, max_length=60, verbose_name='Menú')),
                ('alergias', models.CharField(blank=True, max_length=400, verbose_name='Alergias o restricciones')),
                ('cancion', models.CharField(blank=True, max_length=200, verbose_name='Canción que no puede faltar')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje para los novios')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Recibida')),
            ],
            options={
                'verbose_name': 'Confirmación de asistencia',
                'verbose_name_plural': 'Confirmaciones de asistencia',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=120, verbose_name='Autor')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Mensaje de felicitacion',
                'verbose_name_plural': 'Mensajes de felicitacion',
                'ordering': ['-creado'],
            },
        ),
    ]
