# Generated by Django 6.0.6 on 2026-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula / Documento'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nombre_familia',
            field=models.CharField(blank=True, max_length=120, verbose_name='Familia / Grupo'),
        ),
    ]
