# Generated by Django 6.1.1 on 2026-09-30 17:55

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_confirmacion_cedula_confirmacion_nombre_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombres y apellidos')),
                ('familia', models.CharField(max_length=120, verbose_name='Familia')),
                ('correo', models.EmailField(blank=True, max_length=140, verbose_name='Correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('estado', models.CharField(choices=[('pendiente', 'Sin responder'), ('si', 'Confirmado'), ('no', 'No asistira')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('token', models.SlugField(default=backend.models._token, editable=False, max_length=32, unique=True, verbose_name='Enlace')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('respondido', models.DateTimeField(blank=True, null=True, verbose_name='Respondio')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['familia', 'nombre'],
            },
        ),
    ]
